# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run test on iphone and ipad"
  lane :tests do
    run_tests(
              devices: ["iPhone 13", "iPad Pro (12.9-inch) (5th generation)"],
              scheme: "EldenRingMapTests")
  end

  lane :buildNumber do
    increment_build_number
  end

  lane :patch do
    increment_version_number(
      bump_type: "patch" # Automatically increment patch version number
    )
  end

  lane :feature do
    increment_version_number(
      bump_type: "minor" # Automatically increment minor version number
    )
  end
  lane :release do
    increment_version_number(
      bump_type: "major" # Automatically increment major version number
    )
  end
end
